# Generated by Django 4.2.7 on 2025-10-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_fabric_order_payment_orderfinancials"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="garment_type",
            field=models.CharField(
                choices=[
                    ("shirt", "Shirt"),
                    ("babbar riga", "Babbar Riga"),
                    ("kaftan", "Kaftan"),
                    ("jallabiyya", "Jallabiyya"),
                    ("trouser", "Trouser"),
                    ("suit", "Suit"),
                    ("dress", "Dress"),
                    ("blouse", "Blouse"),
                    ("skirt", "Skirt"),
                    ("coat", "Coat"),
                    ("traditional", "Traditional Wear"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
