# Generated by Django 4.2.7 on 2025-10-04 21:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_order_amount_paid_order_total_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="amount_paid",
            new_name="amount_paid_order",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="total_amount",
            new_name="total_amount_order",
        ),
    ]
