# Generated by Django 4.2.7 on 2025-10-05 10:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0005_rename_amount_paid_order_amount_paid_order_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="amount_paid_order",
        ),
        migrations.RemoveField(
            model_name="order",
            name="total_amount_order",
        ),
    ]
