# Generated by Django 4.2.7 on 2025-10-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0006_remove_order_amount_paid_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="amount_paid",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
