# Generated by Django 4.2.7 on 2025-10-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0010_role_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="agbada_length",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="measurement",
            name="agbada_width",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="measurement",
            name="lap",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
